### ISSUE TITLE
Dataset gives no detectable error but fails to load

### ISSUE THREAD

**Issue by TeunZoer** [KNMI/adaguc-server#380]
Hello,

I ran into an issue I cannot debug because the logs don't seem to giving any error. The problem is that individual files are viewable from the autowms or data directories, but fail to load from datasets even though they are visible in the test window. I added some test files, the configuration file and a legend .svg file I use, hopefully you can recreate the problem that way. 
[files.zip](https://github.com/user-attachments/files/15787995/files.zip)

The netcdf files that are attached are edited to remove the 'plev' dimension (with CDO) and add an 'issue' dimension (with xarray). I would like to create a dataset with 2 dimensions, to be able to browse through time and different forecasts. This seems to work for individual files but not when a dataset is created. I think it should be possible, since I found an example config for Harmonie data that does the same. Could you please help me out?

Thanks in advance!

**Comment by ernstdevreede** [comment]
Hi Teun,


A number of changes are necessary, mostly to the NetCDF file.

The dimension and variable issue is best named forecast_reference_time. The variable forecast_reference_time can be a scalar (without dimension) if each file contains only one run.

The data parameters don't need the issue dimension, but should have the shape (time, lat, lon). The data parameters w and d also need an attribute called grid_mapping with the name of a NetCDF variable that contains the grid description. for example for Harmonie that would be something like:

int64 latitude_longitude ;
latitude_longitude:proj4_params = "+proj=longlat +a=6371229 +e=0 +no_defs" ;
latitude_longitude:grid_mapping_name = "latitude_longitude" ;
and a data parameter would have an attribute like:
        air-temperature-hagl:grid_mapping = "latitude_longitude" ;

The configuration file for a layer would be something like:
  <Layer type="database">
    <Name>Vertical_velocity</Name>
    <Title>Vertical_velocity</Title>
    <Variable>w</Variable>
    <FilePath filter="^.*\.nc$">/data/adaguc-data/EU_IFS_opendata</FilePath>
    <DataPostProc algorithm="ax+b" a="1" b="0" units="Pa s**-1"/>
    <Dimension name="time" interval="PT3H" units="ISO8601" default="min">time</Dimension>
    <Dimension name="forecast_reference_time" interval="PT6H" units="ISO8601">reference_time</Dimension>
    <Styles>vertical_velocity</Styles>
  </Layer>

Hope this helps,

Ernst


________________________________
Van: TeunZoer ***@***.***>
Verzonden: dinsdag 11 juni 2024 14:45:45
Aan: KNMI/adaguc-server
CC: Subscribed
Onderwerp: [KNMI/adaguc-server] Dataset gives no detectable error but fails to load (Issue #380)


Hello,

I ran into an issue I cannot debug because the logs don't seem to giving any error. The problem is that individual files are viewable from the autowms or data directories, but fail to load from datasets even though they are visible in the test window. I added some test files, the configuration file and a legend .svg file I use, hopefully you can recreate the problem that way.
files.zip<https://github.com/user-attachments/files/15787995/files.zip>

The netcdf files that are attached are edited to remove the 'plev' dimension (with CDO) and add an 'issue' dimension (with xarray). I would like to create a dataset with 2 dimensions, to be able to browse through time and different forecasts. This seems to work for individual files but not when a dataset is created. I think it should be possible, since I found an example config for Harmonie data that does the same. Could you please help me out?

Thanks in advance!

**Comment by TeunZoer** [comment]
Hi Ernst,

Thank you very much for your quick response! I will try again with your suggestions. Can I ask how you checked the attributes of the netcdf files? Up till now all 3D files (time, lat, lon)  I used in ADAGUC worked without the grid_mapping attribute. Is this only necessary when you add more dimensions? Or is it necessary now because I manually add dimensions?

Thanks again!

Groetjes Teun
